### ISSUE TITLE
Memory and runtime question

### ISSUE THREAD

**Issue by bryancquach** [COMBINE-lab/TreeTerminus#1]
# Overview

The [TreeTerminus paper](https://doi.org/10.1016/j.isci.2023.106961) has examples of runtime and memory usage in Tables 1 and S1 but no mention of big O or big theta memory and runtime as a function of number of samples. Is this something that is known by the developers for the `group --mean_inf false`, `group --mean_inf true`, and `consenus` commands? If so, would you please report this? I am trying to understand the feasibility of running 200-500 samples with TreeTerminus.

**Comment by NPSDC** [comment]
For the `group` step, we have to scan over all equivalence classes and the transcripts, thus their effective size would be the major contributing factor for time. If `mean_inf` is `false`, then we do these scans over one sample and if mean_inf is true, then over all samples in the experiment in a single `group` step. For most experiments, the number of samples (in your case 400-500) would be much smaller than the number of transcripts.  Thus, from time perspective, group step should easily be able to scale (irrespective if `mean_inf` is set to true or false).
For memory, if `mean_inf` is set to `true`, then all samples along with the inferential replicates of all the transcripts have to be loaded into memory. This might not scale for large number of samples. In the paper, we had 12 samples simulated from human, and the group with mean_inf set to true took 3.2 GBs for 100 inferential replicates. Setting the inferential replicates to 30, when running `Salmon` should help.

`Consensus` another mode, is to be used when `group` with `mean_inf` set to false. We are using PHYLIP's implementation of majority rule extended consensus algorithm with time complexity O(n^3K), where n is the number of leaves/txps and K is the number of samples. Here again the dominating factor is transcripts not samples. We run this step on each connected components in the graph or the subcomponents obtained from a connected component, if transcripts/ (aggregated groups) inside it do not meet a stopping criteria, thus breaking that component into smaller groups, and for most cases the number of transcripts in these components are very small. If `conensus` step is able to run on a small set of samples, then it should be able to run on large number of samples.

I hope this helps.

**Comment by bryancquach** [comment]
> Setting the inferential replicates to 30, when running Salmon should help.

Would it be possible in future releases of TreeTerminus to make it a specifiable option to use less inferential replicates than available? I tried looking at the Salmon output directory files at `<Salmon output directory>/aux_info/bootstrap/` for one of my samples to see if I could manually truncate data from specific inferential replicates, but it seems like the data in this directory are in binary/serialized format. All of my samples are already processed through a pipeline that includes Salmon with 100 inferential replicates.

**Comment by NPSDC** [comment]
We can include that as an option in the future release of TreeTerminus.
