### ISSUE TITLE
Execution of the Consensus Step of TreeTerminus Seemingly Stops Progressing

### ISSUE THREAD

**Issue by linranzhou** [COMBINE-lab/TreeTerminus#2]
I am attempting to execute the consensus step of TreeTerminus to get a summarized forest of trees for 5 samples of an RNA-seq experiment. TreeTerminus starts running, and I see that there are about 220,000 transcripts and 450,000 equivalence classes. 

It runs until the point where it computes a cluster for the group consisting of seemingly all the transcripts. Once it starts computing clusters for the different groups, it arrives at this point in perhaps 1 minute or less. It is at this point that the program seems to stop progressing. The output `cluster_nwk.txt`, `inp_tree.nwk`, and `merged_groups_length.txt` stop increasing in size, and the `out_tree.nwk` file remains empty. 

I have previously allowed the software to run overnight for >8 hours, and it has not progressed any further or terminated after that time. Looking at Tables 1 and 2 of your paper, I wonder if perhaps 220,000 transcripts is too large a number of be practically workable, or if perhaps there is another issue at hand. Thank you.

**Comment by NPSDC** [comment]
Are 220,000 transcripts the total number of transcripts in the experiment or are they the total number of transcripts for the particular group (seems unlikely)? If there are very larger number of transcripts in a group, then consensus might be slow ( see #1) . I have though successfully built a tree with 1000 transcript group. I have not exactly tested at what number of transcripts, the execution of consensus becomes really slow (was never the case for the RNA-Seq samples I tested TreeTerminus on).  If you could upload the screenshot and the `inp_tree.nwk`, that would be helpful.

**Comment by linranzhou** [comment]
Thank you for such a quick response. I have attached to this post the `inp_tree.nwk` file (though renamed to have a `.txt` extension) for the 8 sample run as the consensus step is currently working on that large group. In addition, I have also posted the console output as the consensus works on the large group.

To be more clear, I have about 220,000 transcripts in the experiment with 8 samples. Where it hangs is it gets to a point where it computes a cluster for a very large group. Doing a quick check of the number of elements separated by `_` (the print out to the console states `Computing cluster for group ####_####_######...`), it seems there are about 74,000 transcripts in this group. Based on your comment and the other issue you are referencing, perhaps it is unavoidable that the execution of this step is slow if there is a group that is this large.

I previously did run the consensus step on 5 samples (with ~220,000 transcripts), and it took about 12 hours. I would say almost 100% of that time was spent on computing the cluster for the large group of tens of thousands of transcripts, and all the smaller groups took almost no time at all. As a side note, after the consensus step finished running, it seems like the `inp_tree.nwk` and `out_tree.nwk` files disappeared, leaving only the `cluster_nwk.txt` and `merged_groups_length.txt` files.


[large_group.txt](https://github.com/COMBINE-lab/TreeTerminus/files/14860588/large_group.txt)
[inp_tree_8_samples.txt](https://github.com/COMBINE-lab/TreeTerminus/files/14860618/inp_tree_8_samples.txt)

**Comment by NPSDC** [comment]
I know this is not ideal but currently, we can't do much about this directly. One way to get around this would be to set the parameter `thresh` to true. You can also try out different values of `inf_perc`. This however will not only make the above group but also the other groups smaller. As a feature enhancement, in future versions of TreeTerminus, we could add a parameter that limits the number of transcripts a group can aggregate.

As for the other files `inp_tree` and `out_tree`, they are temporary files that are created during the execution and are deleted later when the program has finished executing.

**Comment by rob-p** [comment]
@NPSDC — We should definitely do some profiling to see if there are obvious algorithmic improvements we can make in the clustering step.

**Comment by linranzhou** [comment]
> I know this is not ideal but currently we can't do much about this directly but atleast it finished executing within 12 hours. One way to get around this would be to set the parameter `thresh` to be true and try different values of `inf_perc`. This however not only make the above group but also the other groups smaller. As a feature enhancement, the future versions of TreeTerminus, we could perhaps add a parameter that limits on the number of txps in a group before it has to break.
> 
> As for the other files `inp_tree` and `out_tree`, they are temporary files that are created during the execution and are deleted later when the program has finished executing.

Thank you so much for the suggestion. Just to make sure, when you mention the parameter `thresh` and the values of `inf_perc`, does that refer to the parameter that sets the minimum proportion of samples the edges have to occur in to be kept when creating the consensus groups (according to your paper, the default is 0.5)? To make our groups smaller (especially the large group of transcripts), do you have suggestions for values to start trying? 

Finally, what is the proper syntax to set `thresh` and try different values of `inf_perc`? Both the README on the repository and the help message you can have TreeTerminus print out only mention the `-d` and `-o` options when running the `consensus` step. Thank you again!

**Comment by NPSDC** [comment]
So I meant to set these parameters for the `group` step. Consensus itself can't do much but works on the input from the `group` step. So `thr` is boolean and should be set to true, which uses a threshold for the reduction in inferential relative variance. Currently, it is set to a default value.  So a group of transcripts will be aggregated, only if the difference in infRV between the group and its underlying transcripts is below this threshold.  Similarly, `inf_perc` can be varied. This directly the infRV of the individual transcripts//nodes, requires them to be greater than the computed threshold, before they can be considered for aggregation. The `inf_perc` can be varied in the current version but we need to allow customizable values for the threshold in reduction in the future version.

**Comment by linranzhou** [comment]
> So I meant to set these parameters for the `group` step. Consensus itself can't do much but works on the input from the `group` step. So `thr` is boolean and should be set to true. For the `inf_perc`, it has be to played with. I would start from `0.8` and then keep going down to `0.1`, to see if the ideal size of groups is observed. However, I realized that that function has a small bug which I will fix over the weekend and then push the new release.

Thank you so much. I will keep an eye out for the new release.

**Comment by NPSDC** [comment]
I have pushed the new release (version 0.3.0). The new flag to try is `red_quant`. I have also modified the above responses (I had mixed up the flags, so would recommend rereading some of my above responses for the description). In short, you can set and play with both `red_quant` and `inf_perc`. A smaller value of `red_quant` and/or a larger value of `inf_perc` leads to smaller groups. The  `inf_perc` (if varied) should not be set close to 1.  Terminus (on top of which TreeTerminus is built) sets the default to `0.25`, which could be a good place to start and then can be played with. The `red_perc`, can be set to 0.025 for small groups or larger than 0.80 for large groups. These are again some rough estimates and can be explored.
